import { Octokit } from "octokit";
import { getGitHubConfig } from "./config";

let _octokit: Octokit | null = null;

function getOctokit(): Octokit {
  if (!_octokit) {
    const { token } = getGitHubConfig();
    _octokit = new Octokit({ auth: token });
  }
  return _octokit;
}

/**
 * Slugify a title for use in branch names.
 * Lowercase, replace non-alphanumeric with hyphens, trim, truncate.
 */
export function slugify(title: string, maxLength = 50): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, maxLength);
}

// ─── Branch Operations ──────────────────────────────────────

interface BranchResult {
  branchName: string;
  sha: string;
}

/**
 * Create a feature branch from latest main.
 * Idempotent — returns existing branch if it already exists.
 */
export async function createFeatureBranch(params: {
  owner: string;
  repo: string;
  issueKey: string;
  issueTitle: string;
}): Promise<BranchResult> {
  const octokit = getOctokit();
  const slug = slugify(params.issueTitle);
  const branchName = `feat/${params.issueKey}-${slug}`;

  // Get latest main SHA
  const { data: mainRef } = await octokit.rest.git.getRef({
    owner: params.owner,
    repo: params.repo,
    ref: "heads/main",
  });
  const mainSha = mainRef.object.sha;

  try {
    // Create branch
    await octokit.rest.git.createRef({
      owner: params.owner,
      repo: params.repo,
      ref: `refs/heads/${branchName}`,
      sha: mainSha,
    });

    console.log(
      `[github] Created branch '${branchName}' from main (${mainSha.slice(0, 7)})`
    );
  } catch (error: unknown) {
    // Branch already exists — that's fine (idempotent)
    if (isGitHubError(error) && error.status === 422) {
      console.log(`[github] Branch '${branchName}' already exists`);
      const { data: existingRef } = await octokit.rest.git.getRef({
        owner: params.owner,
        repo: params.repo,
        ref: `heads/${branchName}`,
      });
      return { branchName, sha: existingRef.object.sha };
    }
    throw error;
  }

  return { branchName, sha: mainSha };
}

// ─── Pull Request Operations ────────────────────────────────

interface PRResult {
  prNumber: number;
  prUrl: string;
  branchName: string;
}

/**
 * Create a pull request for the issue's feature branch.
 * Idempotent — returns existing PR if one already exists.
 * Updates the branch with main before creating the PR.
 */
export async function createPullRequest(params: {
  owner: string;
  repo: string;
  issueKey: string;
  issueTitle: string;
}): Promise<PRResult> {
  const octokit = getOctokit();

  // Find the branch for this issue
  const branchName = await findIssueBranch(
    params.owner,
    params.repo,
    params.issueKey
  );

  if (!branchName) {
    throw new Error(
      `No branch found for ${params.issueKey}. Expected branch with prefix 'feat/${params.issueKey}-'`
    );
  }

  // Check if PR already exists (idempotent)
  const existingPR = await findIssuePR(
    params.owner,
    params.repo,
    params.issueKey
  );

  if (existingPR) {
    console.log(
      `[github] PR #${existingPR.number} already exists for ${params.issueKey}`
    );
    return {
      prNumber: existingPR.number,
      prUrl: existingPR.html_url,
      branchName,
    };
  }

  // Try to update branch with main (forward merge)
  try {
    await octokit.rest.repos.merge({
      owner: params.owner,
      repo: params.repo,
      base: branchName,
      head: "main",
      commit_message: `Merge main into ${branchName}`,
    });
    console.log(`[github] Updated branch '${branchName}' with main`);
  } catch (error: unknown) {
    if (isGitHubError(error) && error.status === 409) {
      throw new Error(
        `Merge conflict: cannot update '${branchName}' with main. Manual resolution needed.`
      );
    }
    // 204 No Content means already up to date — that's fine
    if (isGitHubError(error) && error.status !== 204) {
      throw error;
    }
  }

  // Create the PR
  const linearUrl = `https://linear.app/teamagentic/issue/${params.issueKey}`;
  const { data: pr } = await octokit.rest.pulls.create({
    owner: params.owner,
    repo: params.repo,
    title: `[${params.issueKey}] ${params.issueTitle}`,
    head: branchName,
    base: "main",
    body: [
      `## ${params.issueTitle}`,
      ``,
      `Resolves: [${params.issueKey}](${linearUrl})`,
      ``,
      `---`,
      `*Auto-generated by TeamAgentic webhook service*`,
    ].join("\n"),
  });

  console.log(
    `[github] Created PR #${pr.number} for ${params.issueKey}: ${pr.html_url}`
  );

  return {
    prNumber: pr.number,
    prUrl: pr.html_url,
    branchName,
  };
}

// ─── Auto-Merge Operations ─────────────────────────────────

interface MergeResult {
  merged: boolean;
  sha?: string;
  prNumber?: number;
}

/**
 * Auto-merge (squash) the PR for an issue and delete the branch.
 * Returns error details if merge fails (e.g., conflicts).
 */
export async function autoMergePR(params: {
  owner: string;
  repo: string;
  issueKey: string;
}): Promise<MergeResult> {
  const octokit = getOctokit();

  // Find the PR
  const pr = await findIssuePR(params.owner, params.repo, params.issueKey);

  if (!pr) {
    throw new Error(
      `No open PR found for ${params.issueKey}. Cannot auto-merge.`
    );
  }

  const branchName = pr.head.ref;

  // Merge the PR (squash)
  try {
    const { data: merge } = await octokit.rest.pulls.merge({
      owner: params.owner,
      repo: params.repo,
      pull_number: pr.number,
      merge_method: "squash",
      commit_title: `[${params.issueKey}] ${pr.title}`,
    });

    console.log(
      `[github] Merged PR #${pr.number} (squash) for ${params.issueKey}: ${merge.sha}`
    );

    // Delete the branch
    try {
      await octokit.rest.git.deleteRef({
        owner: params.owner,
        repo: params.repo,
        ref: `heads/${branchName}`,
      });
      console.log(`[github] Deleted branch '${branchName}'`);
    } catch (deleteError) {
      console.warn(
        `[github] Failed to delete branch '${branchName}':`,
        deleteError
      );
      // Non-fatal — branch cleanup is nice-to-have
    }

    return { merged: true, sha: merge.sha, prNumber: pr.number };
  } catch (error: unknown) {
    if (isGitHubError(error) && error.status === 405) {
      throw new Error(
        `Merge conflict on PR #${pr.number} for ${params.issueKey}. Manual resolution needed.`
      );
    }
    throw error;
  }
}

// ─── Helpers ────────────────────────────────────────────────

/**
 * Find the feature branch for an issue by prefix convention.
 */
async function findIssueBranch(
  owner: string,
  repo: string,
  issueKey: string
): Promise<string | null> {
  const octokit = getOctokit();
  const prefix = `feat/${issueKey}-`;

  try {
    // List branches matching the prefix
    const { data: branches } = await octokit.rest.repos.listBranches({
      owner,
      repo,
      per_page: 100,
    });

    const match = branches.find((b) => b.name.startsWith(prefix));
    return match?.name ?? null;
  } catch {
    return null;
  }
}

/**
 * Find an open PR for an issue by branch prefix.
 */
async function findIssuePR(
  owner: string,
  repo: string,
  issueKey: string
): Promise<{ number: number; html_url: string; title: string; head: { ref: string } } | null> {
  const octokit = getOctokit();
  const prefix = `feat/${issueKey}-`;

  const { data: prs } = await octokit.rest.pulls.list({
    owner,
    repo,
    state: "open",
    per_page: 100,
  });

  const match = prs.find((pr) => pr.head.ref.startsWith(prefix));
  return match
    ? {
        number: match.number,
        html_url: match.html_url,
        title: match.title,
        head: { ref: match.head.ref },
      }
    : null;
}

/**
 * Type guard for GitHub API errors with status code.
 */
function isGitHubError(error: unknown): error is { status: number; message: string } {
  return (
    typeof error === "object" &&
    error !== null &&
    "status" in error &&
    typeof (error as Record<string, unknown>).status === "number"
  );
}
