import { Octokit } from "octokit";
import { getGitHubConfig } from "./config";

let _octokit: Octokit | null = null;

function getOctokit(): Octokit {
  if (!_octokit) {
    const { token } = getGitHubConfig();
    _octokit = new Octokit({ auth: token });
  }
  return _octokit;
}

/**
 * Slugify a title for use in branch names.
 * Lowercase, replace non-alphanumeric with hyphens, trim, truncate.
 */
export function slugify(title: string, maxLength = 50): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, maxLength);
}

// ─── Branch Operations ──────────────────────────────────────

interface BranchResult {
  branchName: string;
  sha: string;
}

/**
 * Create a feature branch from the repo's default branch.
 * Idempotent — returns existing branch if it already exists.
 *
 * NOTE: Agents typically create their own branches via git CLI on the mounted
 * repo. This helper remains available for callers that pre-create a branch
 * (e.g. tooling outside the standard agent flow).
 */
export async function createFeatureBranch(params: {
  owner: string;
  repo: string;
  issueKey: string;
  issueTitle: string;
}): Promise<BranchResult> {
  const octokit = getOctokit();
  const slug = slugify(params.issueTitle);
  const branchName = `feat/${params.issueKey}-${slug}`;
  const defaultBranch = await getDefaultBranch(params.owner, params.repo);

  // Get latest SHA of the default branch
  const { data: baseRef } = await octokit.rest.git.getRef({
    owner: params.owner,
    repo: params.repo,
    ref: `heads/${defaultBranch}`,
  });
  const baseSha = baseRef.object.sha;

  try {
    // Create branch
    await octokit.rest.git.createRef({
      owner: params.owner,
      repo: params.repo,
      ref: `refs/heads/${branchName}`,
      sha: baseSha,
    });

    console.log(
      `[github] Created branch '${branchName}' from ${defaultBranch} (${baseSha.slice(0, 7)})`
    );
  } catch (error: unknown) {
    // Branch already exists — that's fine (idempotent)
    if (isGitHubError(error) && error.status === 422) {
      console.log(`[github] Branch '${branchName}' already exists`);
      const { data: existingRef } = await octokit.rest.git.getRef({
        owner: params.owner,
        repo: params.repo,
        ref: `heads/${branchName}`,
      });
      return { branchName, sha: existingRef.object.sha };
    }
    throw error;
  }

  return { branchName, sha: baseSha };
}

// ─── Pull Request Operations ────────────────────────────────

interface PRResult {
  prNumber: number;
  prUrl: string;
  branchName: string;
  noCommits?: boolean;
}

/**
 * Create a pull request for the issue's feature branch.
 * Idempotent — returns existing PR if one already exists.
 * Updates the branch with main before creating the PR.
 */
export async function createPullRequest(params: {
  owner: string;
  repo: string;
  issueKey: string;
  issueTitle: string;
}): Promise<PRResult> {
  const octokit = getOctokit();

  // Find the branch for this issue
  const branchName = await findIssueBranch(
    params.owner,
    params.repo,
    params.issueKey
  );

  if (!branchName) {
    throw new Error(
      `No branch found for ${params.issueKey}. Expected a branch with '${params.issueKey}' in its name.`
    );
  }

  const defaultBranch = await getDefaultBranch(params.owner, params.repo);

  // Check if PR already exists (idempotent)
  const existingPR = await findIssuePR(
    params.owner,
    params.repo,
    params.issueKey
  );

  if (existingPR) {
    console.log(
      `[github] PR #${existingPR.number} already exists for ${params.issueKey}`
    );
    return {
      prNumber: existingPR.number,
      prUrl: existingPR.html_url,
      branchName,
    };
  }

  // Try to update branch with default branch (forward merge)
  try {
    await octokit.rest.repos.merge({
      owner: params.owner,
      repo: params.repo,
      base: branchName,
      head: defaultBranch,
      commit_message: `Merge ${defaultBranch} into ${branchName}`,
    });
    console.log(`[github] Updated branch '${branchName}' with ${defaultBranch}`);
  } catch (error: unknown) {
    if (isGitHubError(error) && error.status === 409) {
      throw new Error(
        `Merge conflict: cannot update '${branchName}' with ${defaultBranch}. Manual resolution needed.`
      );
    }
    // 204 No Content means already up to date — that's fine
    if (isGitHubError(error) && error.status !== 204) {
      throw error;
    }
  }

  // Create the PR
  const linearUrl = `https://linear.app/teamagentic/issue/${params.issueKey}`;

  try {
    const { data: pr } = await octokit.rest.pulls.create({
      owner: params.owner,
      repo: params.repo,
      title: `[${params.issueKey}] ${params.issueTitle}`,
      head: branchName,
      base: defaultBranch,
      body: [
        `## ${params.issueTitle}`,
        ``,
        `Resolves: [${params.issueKey}](${linearUrl})`,
        ``,
        `---`,
        `*Auto-generated by TeamAgentic webhook service*`,
      ].join("\n"),
    });

    console.log(
      `[github] Created PR #${pr.number} for ${params.issueKey}: ${pr.html_url}`
    );

    return {
      prNumber: pr.number,
      prUrl: pr.html_url,
      branchName,
    };
  } catch (error: unknown) {
    // Handle "No commits between X and Y" — branch exists but has no changes
    if (
      isGitHubError(error) &&
      error.status === 422 &&
      error.message?.includes("No commits between")
    ) {
      console.log(
        `[github] No commits on branch '${branchName}' — skipping PR creation`
      );
      return {
        prNumber: 0,
        prUrl: "",
        branchName,
        noCommits: true,
      };
    }
    throw error;
  }
}

// ─── Auto-Merge Operations ─────────────────────────────────

interface MergeResult {
  merged: boolean;
  sha?: string;
  prNumber?: number;
}

/**
 * Auto-merge (squash) the PR for an issue and delete the branch.
 * Returns error details if merge fails (e.g., conflicts).
 */
export async function autoMergePR(params: {
  owner: string;
  repo: string;
  issueKey: string;
}): Promise<MergeResult> {
  const octokit = getOctokit();

  // Find the PR
  const pr = await findIssuePR(params.owner, params.repo, params.issueKey);

  if (!pr) {
    throw new Error(
      `No open PR found for ${params.issueKey}. Cannot auto-merge.`
    );
  }

  const branchName = pr.head.ref;

  // Merge the PR (squash)
  try {
    const { data: merge } = await octokit.rest.pulls.merge({
      owner: params.owner,
      repo: params.repo,
      pull_number: pr.number,
      merge_method: "squash",
      commit_title: `[${params.issueKey}] ${pr.title}`,
    });

    console.log(
      `[github] Merged PR #${pr.number} (squash) for ${params.issueKey}: ${merge.sha}`
    );

    // Delete the branch, then verify it's actually gone — sometimes the API
    // accepts the delete but the branch lingers (transient consistency or a
    // protected-branch policy). If it's still there, retry delete once.
    await deleteBranchWithVerify(
      octokit,
      params.owner,
      params.repo,
      branchName
    );

    return { merged: true, sha: merge.sha, prNumber: pr.number };
  } catch (error: unknown) {
    if (isGitHubError(error) && error.status === 405) {
      throw new Error(
        `Merge conflict on PR #${pr.number} for ${params.issueKey}. Manual resolution needed.`
      );
    }
    throw error;
  }
}

// ─── Close PR (for Cancelled issues) ───────────────────────

interface ClosePRResult {
  closed: boolean;
  prNumber?: number;
  reason: "closed" | "no_pr" | "already_closed";
}

/**
 * Close (without merging) any open PRs for an issue and delete ALL branches
 * that contain the issue key in their name. Used when an issue is moved to
 * Cancelled — we don't want to merge, but we should clean up the repo.
 *
 * Multi-branch cleanup: agents sometimes push to multiple branches for the
 * same issue (e.g. `claude/tea-XX-...` + `feat/TEA-XX-...`). Earlier
 * versions only handled the PR's own branch; this version finds all matches.
 */
export async function closePR(params: {
  owner: string;
  repo: string;
  issueKey: string;
}): Promise<ClosePRResult> {
  const octokit = getOctokit();
  const needle = params.issueKey.toLowerCase();

  // Close all open PRs that match this issue key (usually 0 or 1)
  const { data: openPRs } = await octokit.rest.pulls.list({
    owner: params.owner,
    repo: params.repo,
    state: "open",
    per_page: 100,
  });
  const matchingPRs = openPRs.filter((pr) =>
    pr.head.ref.toLowerCase().includes(needle)
  );

  for (const pr of matchingPRs) {
    await octokit.rest.pulls.update({
      owner: params.owner,
      repo: params.repo,
      pull_number: pr.number,
      state: "closed",
    });
    console.log(
      `[github] Closed PR #${pr.number} for ${params.issueKey} (issue Cancelled)`
    );
  }

  // Delete every branch (open + orphan) that contains the issue key in its name.
  // Skip the default branch as a safety net.
  const defaultBranch = await getDefaultBranch(params.owner, params.repo);
  const { data: branches } = await octokit.rest.repos.listBranches({
    owner: params.owner,
    repo: params.repo,
    per_page: 100,
  });
  const matchingBranches = branches.filter(
    (b) => b.name.toLowerCase().includes(needle) && b.name !== defaultBranch
  );

  for (const b of matchingBranches) {
    await deleteBranchWithVerify(octokit, params.owner, params.repo, b.name);
  }

  if (matchingPRs.length === 0 && matchingBranches.length === 0) {
    return { closed: false, reason: "no_pr" };
  }

  return {
    closed: matchingPRs.length > 0,
    prNumber: matchingPRs[0]?.number,
    reason: matchingPRs.length > 0 ? "closed" : "no_pr",
  };
}

// ─── Helpers ────────────────────────────────────────────────

/**
 * Find the feature branch for an issue.
 *
 * Matches any branch whose name contains the issue key (case-insensitive),
 * since agents may use various conventions like `feat/TEA-24-...`,
 * `claude/tea-24-...`, `pixel/tea-24-...`, etc.
 *
 * Returns the most recently pushed matching branch. Excludes empty branches
 * pointing at the default branch (these are pre-created stubs).
 */
async function findIssueBranch(
  owner: string,
  repo: string,
  issueKey: string
): Promise<string | null> {
  const octokit = getOctokit();
  const needle = issueKey.toLowerCase();

  try {
    const { data: branches } = await octokit.rest.repos.listBranches({
      owner,
      repo,
      per_page: 100,
    });

    const defaultBranch = await getDefaultBranch(owner, repo);
    const defaultSha = branches.find((b) => b.name === defaultBranch)?.commit
      .sha;

    const matches = branches.filter(
      (b) =>
        b.name.toLowerCase().includes(needle) &&
        b.name !== defaultBranch &&
        // Skip stub branches that just point at the default branch (no commits)
        b.commit.sha !== defaultSha
    );

    if (matches.length === 0) return null;

    // Prefer branches NOT starting with `feat/` if multiple match — agents
    // typically use their own prefixes (claude/, pixel/, etc.) for real work.
    const nonStub = matches.find((b) => !b.name.startsWith("feat/"));
    return (nonStub ?? matches[0]).name;
  } catch {
    return null;
  }
}

/**
 * Find an open PR for an issue by matching the issue key in the head branch name.
 */
async function findIssuePR(
  owner: string,
  repo: string,
  issueKey: string
): Promise<{ number: number; html_url: string; title: string; head: { ref: string } } | null> {
  const octokit = getOctokit();
  const needle = issueKey.toLowerCase();

  const { data: prs } = await octokit.rest.pulls.list({
    owner,
    repo,
    state: "open",
    per_page: 100,
  });

  const match = prs.find((pr) => pr.head.ref.toLowerCase().includes(needle));
  return match
    ? {
        number: match.number,
        html_url: match.html_url,
        title: match.title,
        head: { ref: match.head.ref },
      }
    : null;
}

/**
 * Fetch the repo's default branch (e.g. "main", "master").
 */
async function getDefaultBranch(owner: string, repo: string): Promise<string> {
  const octokit = getOctokit();
  const { data } = await octokit.rest.repos.get({ owner, repo });
  return data.default_branch;
}

/**
 * Type guard for GitHub API errors with status code.
 */
function isGitHubError(error: unknown): error is { status: number; message: string } {
  return (
    typeof error === "object" &&
    error !== null &&
    "status" in error &&
    typeof (error as Record<string, unknown>).status === "number"
  );
}

/**
 * Delete a branch, then verify it's actually gone. If it's still there after
 * the delete call returns success (transient consistency / protected-branch
 * silent failure), retry once. All failures are non-fatal — log + move on.
 */
async function deleteBranchWithVerify(
  octokit: Octokit,
  owner: string,
  repo: string,
  branchName: string
): Promise<void> {
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      await octokit.rest.git.deleteRef({ owner, repo, ref: `heads/${branchName}` });
    } catch (deleteError) {
      // 422 "Reference does not exist" means it's already gone — success.
      if (isGitHubError(deleteError) && deleteError.status === 422) {
        console.log(`[github] Branch '${branchName}' already deleted`);
        return;
      }
      console.warn(
        `[github] deleteRef '${branchName}' (attempt ${attempt + 1}) failed:`,
        deleteError
      );
      // Fall through to verify — maybe it succeeded anyway.
    }

    // Verify by trying to fetch the branch — expect 404.
    try {
      await octokit.rest.repos.getBranch({ owner, repo, branch: branchName });
      // Still exists — log and (on first attempt) retry the delete.
      if (attempt === 0) {
        console.warn(
          `[github] Branch '${branchName}' still exists after delete — retrying`
        );
        continue;
      }
      console.warn(
        `[github] Branch '${branchName}' still exists after retry — giving up`
      );
    } catch (getError) {
      if (isGitHubError(getError) && getError.status === 404) {
        console.log(`[github] Deleted branch '${branchName}'`);
        return;
      }
      // Unexpected error verifying — log and stop. Branch may or may not be gone.
      console.warn(
        `[github] Could not verify deletion of '${branchName}':`,
        getError
      );
      return;
    }
  }
}
